repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        language_version: python3
        exclude: /(migrations|_pb2)/
        args: [ -r,  -c ,".bandit_scan.cfg", -f , "txt",  -o , "bandit_scan.log", "--exit-zero", $(git ls-files) ]