name: CI
on: [push, workflow_dispatch]

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{matrix.os}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Build and run Phorge
        run: |
          cd tests/
          docker build -t phorge .
          docker run -d -p 8080:80 --rm --name phorge phorge
      - name: unittest
        run: |
          sudo apt install python3 python3-venv -y
          python3 -m venv ci
          source ci/bin/activate
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pre-commit run -a
          pytest
